spring.application.name=dashboard


# Server Configuration

server.port=8080
server.servlet.context-path=/api
 

# Database Configuration

spring.datasource.url=jdbc:mysql://localhost:3306/finance_dashboard?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=ksp@051203
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 

# JPA / Hibernate Configuration

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
 

# JWT Configuration

app.jwt.secret=MySuperSecureSecretKeyThatIsAtLeast32Bytes!
app.jwt.expiration-ms=86400000
 

# Logging

logging.level.com.finance.dashboard=DEBUG
logging.level.org.springframework.security=INFO
 

# Pagination defaults

app.pagination.default-page-size=10
app.pagination.max-page-size=100
 

# SpringDoc / Swagger

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
